apiVersion: v1
kind: ServiceAccount
metadata:
  name: nic-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nic-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - patch
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nic-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nic-controller
subjects:
  - kind: ServiceAccount
    name: nic-controller
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
spec:
  selector:
    matchLabels:
      app: nic-controller
  template:
    metadata:
      labels:
        app: nic-controller
    spec:
      serviceAccountName: nic-controller
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      containers:
        - name: nic-controller
          image: 192.168.80.240:4000/jalapeno/nic-controller-debug:0.0.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          args:
            - --v
            - "5"
          volumeMounts:
            - name: sysfs
              mountPath: /sys
      nodeSelector:
        jalapeno.io/infra-app-nic-controller: nic-controller
      volumes:
        - name: sysfs
          hostPath:
            path: /sys
metadata:
  name: nic-controller
  namespace: default
